# Generated by Django 5.0 on 2023-12-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='number',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
