# Generated by Django 5.0 on 2023-12-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_id', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('time_in_hospital', models.IntegerField()),
                ('n_lab_procedures', models.IntegerField()),
                ('n_medications', models.IntegerField()),
                ('n_outpatient', models.IntegerField()),
                ('n_emergency', models.BooleanField()),
                ('n_inpatient', models.IntegerField()),
                ('n_diagnoses', models.IntegerField()),
            ],
        ),
    ]
