# Generated by Django 5.0 on 2023-12-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_encounter_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='time_in_hospital',
            field=models.CharField(max_length=5),
        ),
    ]
