# Generated by Django 5.0 on 2023-12-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_encounter_time_in_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='n_emergency',
            field=models.IntegerField(),
        ),
    ]
